service: service
frameworkVersion: '3'

plugins:
  - serverless-plugin-log-retention

provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    apiGateway: true
    lambda: true
  stage: dev
  region: us-east-1

custom:
  logRetentionInDays: 7

functions:
  hello:
    handler: handler.hello
    environment:
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
      # OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /service-dev-hello/otel-config.yml
    events:
      - http:
          path: /test
          method: get
    layers:
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-2-0:1

