service: service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    apiGateway: true
    lambda: true
  stage: dev
  region: us-east-1
  logRetentionInDays: 7

functions:
  hello:
    handler: handler.hello
    environment:
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
      #this is optional and only necessary if you want to tweak something
      # OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yml
    events:
      - http:
          path: /test
          method: get
    layers:
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-2-0:1

